config/routes.rb
Rails.application.routes.draw do
  get '/top' => 'homes#top'
  
  # listsコントローラの同じ名前のアクションに紐づく形で自動的に振り分け
  resources :lists
  
  # get 'lists/new'
  # # postは新規投稿
  # post 'lists' => 'lists#create'
  # get 'lists' => 'lists#index'
  # # lists/:id = lists/1やlists/3を表す
  # # , as: '名前'で名前に記入したものを代数として設定できる。as 〜として
  # get 'lists/:id' => 'lists#show', as: 'list'
  # get 'lists/:id/edit' => 'lists#edit', as: 'edit_list'
  # patch 'lists/:id' => 'lists#update', as: 'update_list'
  # delete 'lists/:id' => 'lists#destroy', as: 'destroy_list'
  # get '/top' => 'homes#top'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  #1. $ rails active_storage:install
  #2. $ rails g scaffold user name portrait:attachment(portraitというActive Storage用属性を追加する)
  #3.rails db:migrate
  #4.1対１(単数枚画像投稿)で関連付けるという宣言
  has_one_attached :image
   # 1対多(複数枚画像投稿)で関連付けるという宣言
  # has_many_attached :portrailts
  
  # validates :対象のカラム名, presence(存在): true
  validates :title, presence: true
  validates :body, presence: true
  validates :image, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  # インスタンス変数は指定しておかないとviewファイルで使えない
  def new
    # 空のインスタンスを作成＠はviewファイルに渡すときに使うインスタンス変数
    @list = List.new
  end

  def create
    # データを受け取り空のインスタンスを作成,(list_params)はストロングパラメータ
    @list = List.new(list_params)
    # 代入したデータを保存
    if @list.save
      flash[:notice] = "投稿に成功しました"
      # list_path = "/lists/#{list.id}" list_pathのlistはroutesの〜,as:で設定した値
      redirect_to list_path(@list.id)
    else
      # indexにリダイレクトするにはindexと同じ処理をする必要がある。
      # index.htmlには@listsが定義。@lists = List.allであるため同じように追記
      # @lists = List.all
      # render :index
      render :new
    end
  end

  def index
    # @lists：全件表示の為複数形、List.all:リストに入力してあるもののすべてのデータ
    @lists = List.all
  end

  def show
    # paramas[:id]は対象のidを表す。id:1なら、List.find(1)のような処理になる
    @list = List.find(params[:id])
  end

  def edit
    @list = List.find(params[:id])
  end
  
  def update
    # idの一致するデータを探し＠listに代入
    list =List.find(params[:id])
    # @listをアップデート
    if list.update(list_params)
      flash[:notice] = "編集に成功しました"
      redirect_to list_path(list.id)
    else
      render :edit
    end
  end

  def destroy
    list = List.find(params[:id])
    list.destroy
    redirect_to '/lists'
  end
  # ストロングパラメータrequire(:モデル名).permit(:許可するカラム名,~)
  private
  def list_params
    params.require(:list).permit(:title, :body,:image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/homes/top.html.erb
<h1>Homes#top</h1>
<p>Find me in app/views/homes/top.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--新しい書体の呼び込み-->
    <link href="https://fonts.googleapis.com/css?family=Kaushan+Script" rel="stylesheet">
  </head>
  
  <body>
    <header>
      <h1 class="headline"> All Lists </h1>
    </header>
    <nav>
      <ul class="nav-list">
        <li class="nav-list-item">
          <%= link_to "Top", top_path %>
        </li>
        <li class="nav-list-item">
          <%= link_to "Lists", lists_path %>
        </li>
        <li class="nav-list-item">
          <%= link_to "New List", new_list_path %>
        </li>
      </ul>
    </nav>
    <main>     
      <%= yield %>
    </main>
  </body>
</html>

app/views/lists/edit.html.erb
<h1>編集画面</h1>
<!--update_list はroutesの,as: 'update_path'で設定した。patchは更新の意味-->
<!--resources :listsに変更。routesにupdateはlist + patchとあるので変更-->
<%= form_with model: @list, url: list_path(@list.id), method: :patch do |f| %>
  <h4>タイトル</h4>
  <%= f.text_field :title %>
  <h4>本文</h4>
  <%= f.text_area :body %>
  <%= f.submit '保存' %>
<% end %>

app/views/lists/index.html.erb
<!--wrap = 包む-->
<div class="list-wrap">
  <!--@list = List.allのデータをeach文で配列。代数はlist-->
<!--%=の=は不要、htmlとして表示する理由がないため-->
<% @lists.each do |list| %>
 <!--list.title,list.body,list.image,list.idのlistはeach文の代数のlist-->
  <div class="list-box">
     <!--list.iamgeがあればtrue-->
    <% if list.image.attached? %>
       <!--image_tag データ元,サイズ。サイズ間は小文字のエックス(x)要注意！-->
      <%= image_tag list.image, size: "200x200" %>
    <% else %>
      <!--falseであった場合no_imageを表示する-->
      <%= image_tag 'no_image', size: "200x200" %>
    <% end %>
    <div class="list-comment">
      <span class="list-body"><%= list.body %></span>
                              <!--link_to 表示名, "/リンク先のurl"  ,忘れに注意-->
      <span class="list-title"><%=link_to list.title, list_path(list.id) %></span>
    </div>
  </div>
<% end %>
</div>

app/views/lists/new.html.erb
<h1>新規投稿</h1>
<!--もしエラーが有るとき errors =true-->
<% if @list.errors.any? %>
<!--エラーの数をcountで数え表示-->
  <%= @list.errors.count %>件のエラーが発生しました
  <!--エラーの内容をeach文で呼び出し、記述-->
   <ul>
    <% @list.errors.full_messages.each do |message| %>
    <!--messageはeach doの後で定義したmessage-->
     <li><%= message %></li>
    <% end %>
   </ul>
<% end %>

<!--form_with model: [モデル名@list = List.new],url: 送信先,method: :タイプ do |f|-->
<%= form_with model: @list, url: '/lists', method: :post do |f| %>


 <h4>タイトル</h4>
 <!--text_field 一行の入力欄-->
 <%= f.text_field :title %>

 <h4>本文</h4>
 <!--text_area 複数行の入力欄-->
 <%= f.text_area :body %>
 
  <h4>画像</h4>
  <!--file_fieldはファイルを投稿するフィールド、accept: "image/*"でimageのみ-->
  <%= f.file_field :image, accept: "image/*" %>
  <!--submitは送信ボタン。投稿はそのボタンに表示するもの-->
<%= f.submit '投稿' %>
<% end %>

app/views/lists/show.html.erb
<div class ="flash_box">
  <%= flash[:notice] %>
</div>

<h2>タイトル</h2>
<p><%= @list.title %></p>
<h2>本文</h2>
<p><%= @list.body %></p>

 <p>画像</p>
 <!--list.iamgeがあればtrue-->
 <% if @list.image.attached? %>
 <!--image_tag データ元,サイズ-->
   <%= image_tag @list.image, size: "300x300" %>
 <% else %>
<!--falseであった場合no_imageを表示する-->
   <%= image_tag 'no_image', size: "300x300" %>
 <% end %>
<%= link_to "編集", edit_list_path(@list.id) %>
<!--resources :listsに変更。routesにdeleteはlist + deleteとあるので-->
<%= link_to "削除", list_path(@list.id),method: :delete, "data-confirm" => "本当に削除しますか？" %>